services:
  - type: web
    name: todo-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MongoDbSettings__ConnectionString
        sync: false
      - key: AllowedOrigins
        sync: false
